# Generated by Django 2.2.7 on 2019-11-23 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='portfilio_site',
            new_name='portfolio_site',
        ),
    ]
